### GENERAL SETTINGS ###

# Site settings
title: eTrilles_
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #UA-50546869-2
baseurl: "/personal" #important: start with /
url: "https://argodyne.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://www.linkedin.com/in/etrilles/
  - title: github
    url: https://github.com/Argodyne?tab=repositories
  #- title: twitter
  #  url:
  #- title: instagram
  #  url:
  #- title: tumblr
  #  url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
#address:
#  - lines:
#    - Some Ave, 987,
#    - 23890, New York,
#    - United States.
email: TrillesAndreo@gmail.com
#tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Enrique Trilles Andreo
    # position: CEO
    text: Mi descripcion, en config_.yml
    img: team01.jpg # TODO: foto personal aqui!
    social:
      - title: envelope #use for email address
        url: mailto:TrillesAndreo@gmail.com
      - title: linkedin
        url: https://www.linkedin.com/in/etrilles/


# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "About text found at _config yml file!"
